### ISSUE TITLE
PSIO support would be amazing (BIN file) as of now it stays at "Initiliazing CD"

### ISSUE THREAD

**Issue by Nashismo** [alex-free/tonyhax#13]
Dear Alex:

I am a user of PSIO and this ODE has many compatibility issues. If I could use your hack by simply loading the BIN image through PSIO would be amazing!

Well, that is what I thought! I said I'm just gonna load the BIN image and start Tonyhax from there! It starts, but it stays at Initializing CD.

I always use a correctly burned CD of FF7 (a game that gives me issues on PSIO) and I have also tried with original games (Japenese original game as this console is Japanese).

I figure it has to do with something PSIO does by leaving the lens unusable after loading an Image file.

If you have any advice or a way to allow us PSIO users to use your software, I would be forever grateful. 

My very best regards, Nashismo.

**Comment by alex-free** [comment]
> Dear Alex:
> 
> I am a user of PSIO and this ODE has many compatibility issues. If I could use your hack by simply loading the BIN image through PSIO would be amazing!
> 
> Well, that is what I thought! I said I'm just gonna load the BIN image and start Tonyhax from there! It starts, but it stays at Initializing CD.
> 
> I always use a correctly burned CD of FF7 (a game that gives me issues on PSIO) and I have also tried with original games (Japenese original game as this console is Japanese).
> 
> I figure it has to do with something PSIO does by leaving the lens unusable after loading an Image file.
> 
> If you have any advice or a way to allow us PSIO users to use your software, I would be forever grateful.
> 
> My very best regards, Nashismo.

I could see why this would happen, as I believe the PSIO takes control away from the optical drive. Tonyhax would then never get the correct interrupts back from the actual CD drive, only PSIO I'd imagine?

Looking at the PSIO FAQ, there is a section which states if you don't have a modchip already you can't boot CD-R backups using the boot disc option, and they refuse to add support for that, which is kind of weird imo.

The problem here is I don't know how PSIO 'takes control' of the CD drive, in order to make this work I would need their ROM loader code at bare minimum to figure out how to 'give back' control to the real CD drive after loading the BIN. As this is a proprietary product, I can't really do that, there is no way they will release their code,

You could always buy an extremely cheap Japanese game with a save game exploit (literally only a few dollars), and you can boot that real Japanese game to start the loader via a save game exploit ( https://alex-free.github.io/tonyhax-international/save-game-exploit.html ) using that PSIO 'boot CD' option that for whatever reason, only supports booting real discs.

I know this isn't the answer your looking for, I wish there was more I could do. I can't think of any way I could work around this without the PSIO ROM loader code.

**Comment by Nashismo** [comment]
I understand Alex, and it is fascinating to read how all this works! And yes, it is weird PSIO team does not allow for CD backup loading, they say it is because that would be illegal, how ridiculous that is, is beyond me really. 

Because they sell a product specifically for that, what difference does it make if you play backups from a burned disc or an ISO on the PSIO? It is just as legal/illegal.

Thank you Alex, it is good to know though, I thank you for your time and keep going with this great work!

But you know what other work seems amazing and maybe you could contribute too on your next project? DKWDRV https://github.com/wisi-w/DKWDRV/releases/tag/1.0 

A PS1 loader for PS2!

It is supposed to work with Tonyhax but it is made for PS2 consoles that use PS1 emulation, it is supposed to be more compatible than PS2 consoles that use real PS1 hardware, as it works in a completely different way (can't remember the details). 

I personally would love to as I only have a PS2 Slim 9000 :)

Ok, thanks then, for everything!

**Comment by alex-free** [comment]
> I understand Alex, and it is fascinating to read how all this works! And yes, it is weird PSIO team does not allow for CD backup loading, they say it is because that would be illegal, how ridiculous that is, is beyond me really.
> 
> Because they sell a product specifically for that, what difference does it make if you play backups from a burned disc or an ISO on the PSIO? It is just as legal/illegal.
> 
> Thank you Alex, it is good to know though, I thank you for your time and keep going with this great work!
> 
> But you know what other work seems amazing and maybe you could contribute too on your next project? DKWDRV https://github.com/wisi-w/DKWDRV/releases/tag/1.0
> 
> A PS1 loader for PS2!
> 
> It is supposed to work with Tonyhax but it is made for PS2 consoles that use PS1 emulation, it is supposed to be more compatible than PS2 consoles that use real PS1 hardware, as it works in a completely different way (can't remember the details).
> 
> I personally would love to as I only have a PS2 Slim 9000 :)
> 
> Ok, thanks then, for everything!

You know, I always thought it was weird that Tonyhax didn't support SCPH-50000+ consoles. I know the reason for the original Tonyhax is because the unlock commands are not there, I believe it is treated as a Japanese console.

That is actually perfect though for Tonyhax International, if it indeed detects a SCPH-50000+ console as Japanese it should 'just work' because the Japanese code path does not use unlock commands (but instead an artificial swap trick). If one could mess with the lid sensor correctly on a slim PS2, or even just use a swap magic tool (like the SCPH-10000 through SCPH-39000 Japanese PS2 consoles that are already supported by Tonyhax International) it should work I would think.

All I have PS2 wise though is 2 SCPH-10000s and one SCPH-30001 (which is having issues reading any PS1 discs as of late, the 10000s are rock solid though). I never really thought there was a need for Tonyhax International on newer PS2s.

If there is indeed a need, I would try it on a slim PS2 via the save game exploit. The SCPH-90000 should just work like that if you can manually manipulate the lid sensor on that model (I'd look into YouTube). Is there really no PS1 backup loader method for that model?

**Comment by Nashismo** [comment]
I have searched for years and there really isn't a loader method for PS1 backups on the PS2, at least not native.

For example, Open PS2 Loader cannot go into PS1 mode, because OPL uses the ethernet or USB ports on the PS2, and you go to PS1 mode, you simply don't have access to that hardware, as of course the PS1 didn't have those things.

And honestly not even chips work, I have modded my PS2 Slim 9000 and done everything according to tutorials for installing the chip with PS1 support, and yet, it simply doesn't work. And I have a PSONE, and use good media (Verbatim) and my backups work perfectly on my PSONE, but the PS2, I have never been able to! :)

My idea was simply that maybe you could these guys working at DKWDRV as they are in Beta stages still.

Thank you again for talking and sharing.

**Comment by alex-free** [comment]
> I have searched for years and there really isn't a loader method for PS1 backups on the PS2, at least not native.
> 
> 
> 
> For example, Open PS2 Loader cannot go into PS1 mode, because OPL uses the ethernet or USB ports on the PS2, and you go to PS1 mode, you simply don't have access to that hardware, as of course the PS1 didn't have those things.
> 
> 
> 
> And honestly not even chips work, I have modded my PS2 Slim 9000 and done everything according to tutorials for installing the chip with PS1 support, and yet, it simply doesn't work. And I have a PSONE, and use good media (Verbatim) and my backups work perfectly on my PSONE, but the PS2, I have never been able to! :)
> 
> 
> 
> My idea was simply that maybe you could help these guys working at DKWDRV as they are in Beta stages still.
> 
> 
> 
> Thank you again for talking and sharing.
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

Hmm, have you tried using the save game exploit on your PS2 with a supported game? I'd imagine it would work even though it isn't officially supported. You'd need to figure out how to manipulate the lid sensor on the slim models, I know it's possible with at least the SCPH-7000X series and I can't imagine it is that different for your slightly newer model. I think you have to open the console up to gain access to the lid sensor though, it's hidden internally (and I think there are multiple). 

If you get a chance, try this out and let me know.

**Comment by Nashismo** [comment]
Actually, now using DKWDRV.ELF you are supposed to be able to access Tonyhax! And this is quite a new sofmod of course, I will be trying this and see how it works and see if I can load Tonyhax international. I will let you know! Thank you Alex for your time.

**Comment by Nashismo** [comment]
I tried to make it work (on a USA NTSC PS2 9000), but I only have original PS1 Japanese games! So it doesn't work for me hahahaha. I am sorry Alex, I didn't want to waste your time.
