### ISSUE TITLE
Planet Laika freezes at title (english patch version)

### ISSUE THREAD

**Issue by JMaxxL** [alex-free/tonyhax#39]
Not sure if this counts as copy protection issue or not since its a English patch but this game would not play it froze at title on cheat cart international v1.3.7 SCPH-7501 verbatim burnt at 8x 

after applying
https://www.romhacking.net/translations/6451/
this patch game started freezing using tonyhax international via cheat cart.

**Comment by JMaxxL** [comment]
you think you will fix this or since its just a patch dose it not really count, anyway I removed video just not going mention it since its a patched game

**Comment by alex-free** [comment]
Is it possible that this patch doesn't work on real hardware? To rule that out I have a mod-chipped SCPH-5501 that I will try to use without any soft-mod. 

Does the same happen with UniROM and original Tonyhax v1.4.5?

I looked at the patch notes and I'm not sure if real hardware was ever tried:

Patch Notes/Warnings
======================================================
We joked a little about this game being an
emulator killer, in that quite a few tried-and-true
emulators just don't work. However, I cleared it
on ePSXe, and others testing it cleared it on
duckstation and Mednafen. If you're having a gameplay issue or
a freeze, feel free to post about it, but also
see if swapping emulators works for you.

Known emulators to break are pcsx and No$psx.

Nothing else so far. 
If you happen to find anything, do let us know!

**Comment by alex-free** [comment]
Alright, I just tested this 3 different ways. Media is CMC Pro burned at 2x speed with IOMEGA ZIP CD 650 USB + CDRDAO-PLED using cdrdao write --speed 4 --swap --eject -n --driver generic-mmc-raw *.cue:

SCPH-1000 (no mod-chip): Fully playable.
SCPH-5501 (non-stealth mod-chip, no soft-mod): Fully playable.
SCPH-5501 (non-stealth mod-chip, with International v1.3.7 GameShark): Fully playable.

Highly think this is a disc read issue so closing for now.

**Comment by alex-free** [comment]
Have a theory on this, hoping it pans out.  Testing possible fix now.

**Comment by alex-free** [comment]
LMAO BRO I FIXED IT FIRST TRY! The downside is that you can't use GameShark codes with this game using my current fix (currently, maybe somehow I might be able to fix that eventually).

So the whole issue is, remember when I first released the gameshark code feature and it only worked on my SCPH-5501 and on no other models of console? That was because the gameshark code feature relies on using 'reserved'/'unused' kernel RAM to store the actual codes it parses during the game by the cheat engine. This area of RAM is 0xD000-0xDF78. Now the issue with the original GameShark code implementation was that every console except the SCPH-5501 was not gaurenteed to have a zeroed out memory region here (even though it is unused for every console model, some garbage AFAICT is stored here in other BIOS/models). That was screwing up the cheat engine parsing routines, which made the gameshark code engine not work on that first build of International that had gameshark support if it was used on literally any other BIOS/model.

So get this, I was looking at this issue and I noticed hey, the SCPH-1000 is working but the SCPH-5501 is not when both are using the same International cheat cart (v1.3.7). So I changed around the code which clears the RAM for the cheat engine to work to only do the clearing of RAM if the cheat engine functionality is active. BOOM! It works on the 5501 now, and every other console!

So how this translation patch works is it is using the 'unused RAM' (the same RAM International needs for the gameshark support, it's literally the same idea, use the unused RAM) for whatever code additions it needs to make the translation work.

v1.3.8 beta 2 works with this game 100% now with all console models. Please confirm for me. This build also has the improved memory card handling for gameshark codes. Just remember, with this specific game, gameshark code functionality will cause this same issue if activated by pressing O to read the memory card.

[tonyhax-international-v1.3.8b2.zip](https://github.com/alex-free/tonyhax/files/12503239/tonyhax-international-v1.3.8b2.zip)

Really great bug report man! Keep it up.
