### ISSUE TITLE
Need instructions regarding missing ROM file in Tonyhax ROM Flasher's BIN/CUE image

### ISSUE THREAD

**Issue by Username173** [alex-free/tonyhax#63]
I noticed that the tonyhax-international-v1.5.2.rom file is missing from the disc image. I sacrificed one CD-R disc to try manually copy pasting files from the disc image alongside with the rom file, but Unirom fails to find any files from the disc and even crashes.
Is the only method of finding the rom file in the program is through use of the parallel connection to the PC, or is there a method which would let me burn the image so that the rom file would also be included?

**Comment by alex-free** [comment]
The intended way is to use the included rom flasher cd: 

https://github.com/alex-free/tonyhax/blob/master/flashed-cheat-cart.md#flashing-your-cheat-cart-with-the-rom-flasher-cd-r

That is a standalone boot-able CD that will flash most cheat carts with the Tonyhax International loader. Some cheat carts do not work with it, and for those cases the current instructions are to indeed use UniROM with  Parallel connection to the PC to flash the tonyhax-international-v1.5.2.rom file.

Some people have modified the Unirom CD to include the rom file as well. That isn't something I've done or have documented.

I could add the .rom file into the boot cd or rom flasher cd disc images, so that in theory Unirom would be able to pick it up as well. I had never really thought about that before as I just use the standalone boot-able rom flasher cd.

**Comment by Username173** [comment]
The BIN/CUE did have the ROM file needed, in which I now managed to successfully flash the cart. I don't know if one of previous releases didn't have the ROM file included or if something happened during Imgburn's disc burning process, because I remember it not having the rom file when I first time attempted to flash the cart before going for Unirom's ROM Flasher.
